### PR TITLE
Implement ino64 related syscalls. Fix signal(3) emulation.

### PR DESCRIPTION
**Pull request by strejda**

### CODE REVIEW

**Comment by seanbruno** [comment]
Hrm ... the linking for non-static case isn't quite right.  Do you have time to look at this?

 LINK    arm-bsd-user/qemu-arm
bsd-user/syscall.o: In function `do_bsd_freebsd11_mknod':
/home/sbruno/bsd/qemu-bsd-user/bsd-user/bsd-file.h:748: undefined reference to `freebsd11_mknod'
bsd-user/syscall.o: In function `do_freebsd11_stat':
/home/sbruno/bsd/qemu-bsd-user/bsd-user/freebsd/os-stat.h:85: undefined reference to `freebsd11_stat'
bsd-user/syscall.o: In function `do_freebsd11_lstat':
/home/sbruno/bsd/qemu-bsd-user/bsd-user/freebsd/os-stat.h:101: undefined reference to `freebsd11_lstat'
bsd-user/syscall.o: In function `do_freebsd11_nstat':
/home/sbruno/bsd/qemu-bsd-user/bsd-user/freebsd/os-stat.h:181: undefined reference to `freebsd11_nstat'
bsd-user/syscall.o: In function `do_freebsd11_nfstat':
/home/sbruno/bsd/qemu-bsd-user/bsd-user/freebsd/os-stat.h:195: undefined reference to `freebsd11_nfstat'
bsd-user/syscall.o: In function `do_freebsd11_fhstat':
/home/sbruno/bsd/qemu-bsd-user/bsd-user/freebsd/os-stat.h:275: undefined reference to `freebsd11_fhstat'
bsd-user/syscall.o: In function `do_freebsd11_statfs':
/home/sbruno/bsd/qemu-bsd-user/bsd-user/freebsd/os-stat.h:350: undefined reference to `freebsd11_statfs'
bsd-user/syscall.o: In function `do_freebsd11_fstatfs':
/home/sbruno/bsd/qemu-bsd-user/bsd-user/freebsd/os-stat.h:384: undefined reference to `freebsd11_fstatfs'
bsd-user/syscall.o: In function `do_freebsd11_fhstatfs':
/home/sbruno/bsd/qemu-bsd-user/bsd-user/freebsd/os-stat.h:314: undefined reference to `freebsd11_fhstatfs'
bsd-user/syscall.o: In function `do_freebsd11_fstatat':
/home/sbruno/bsd/qemu-bsd-user/bsd-user/freebsd/os-stat.h:146: undefined reference to `freebsd11_fstatat'
bsd-user/syscall.o: In function `do_bsd_freebsd11_mknodat':
/home/sbruno/bsd/qemu-bsd-user/bsd-user/bsd-file.h:762: undefined reference to `freebsd11_mknodat'
bsd-user/syscall.o: In function `do_freebsd11_fstat':
/home/sbruno/bsd/qemu-bsd-user/bsd-user/freebsd/os-stat.h:115: undefined reference to `freebsd11_fstat'
bsd-user/syscall.o: In function `do_freebsd11_getdirentries':
/home/sbruno/bsd/qemu-bsd-user/bsd-user/freebsd/os-stat.h:528: undefined reference to `freebsd11_getdirentries'
bsd-user/syscall.o: In function `do_freebsd11_getdents':
/home/sbruno/bsd/qemu-bsd-user/bsd-user/freebsd/os-stat.h:496: undefined reference to `freebsd11_getdents'
bsd-user/syscall.o: In function `do_freebsd11_nlstat':
/home/sbruno/bsd/qemu-bsd-user/bsd-user/freebsd/os-stat.h:210: undefined reference to `freebsd11_nlstat'
bsd-user/syscall.o: In function `do_freebsd11_getfsstat':
/home/sbruno/bsd/qemu-bsd-user/bsd-user/freebsd/os-stat.h:430: undefined reference to `freebsd11_getfsstat'
/home/sbruno/bsd/qemu-bsd-user/bsd-user/freebsd/os-stat.h:420: undefined reference to `freebsd11_getfsstat'
bsd-user/syscall.o: In function `do_freebsd_getfsstat':
/home/sbruno/bsd/qemu-bsd-user/bsd-user/freebsd/os-stat.h:459: undefined reference to `freebsd11_getfsstat'

**Comment by strejda** [comment]
Can you give me more details, please?  Mainly configure arguments, FreeBSD version + svn revision. I don't have problems to compile this on actual current and stable.

**Comment by strejda** [comment]
Oki, I found where is problem. Just testing fix.

**Comment by seanbruno** [comment]
Are you going to change the invocations of the freebsd11_  compat functions to just direct syscalls?

**Comment by seanbruno** [comment]
I talked to kib@ about this and he reminded me that the freebsd11 compat functions are not exported into a library ... so you can't just "make them work".  One has to use the syscall() directly, I think.

**Comment by strejda** [comment]
FreeBSD 11 compat functions are exported, with original name but different symbol version.
So only proper decoration is missing from original patch.
But I agree, calling all syscalls directly, without clib shim is only way to move forward. Moreover, it's a prerequisite for safe_syscall implementation.

**Pull request merged**
