### PR TITLE
os-thread: update state appropriately after updating reader count

### PR DESCRIPTION
**Pull request by kevans91**
The later unlock_user_struct call would get optimized out due to the lack of
update in this path. This should fix many of the apparent hangs reported by
many.

Diagnosed by:	Mark Millard <marklmi at yahoo.com>
Submitted by:	Mark Millard <marklmi at yahoo.com>

### CODE REVIEW

**Comment by bsdimp** [comment]
This looks good to me. Did Mark say it fixed things for him?

**Comment by strejda** [comment]
Imho, this is wrong way - target_urwlock->rw_state is atomic variable and using value from reread breaks its atomicity.   And same is true for previous for loop. Moreover, I'm not sure about TARGET_EPERM returns. Both looks wrong but I have no idea about their functionality.

Something like this looks more appropriate (untested, uncompiled):

```
diff --git a/bsd-user/freebsd/os-thread.c b/bsd-user/freebsd/os-thread.c
index e298073181..e75d39ce07 100644
--- a/bsd-user/freebsd/os-thread.c
+++ b/bsd-user/freebsd/os-thread.c
@@ -1242,34 +1242,35 @@ abi_long freebsd_rw_unlock(abi_ulong target_addr)
     }

     __get_user(flags, &target_urwlock->rw_flags);
+retry:
     __get_user(state, &target_urwlock->rw_state);

     if (state & TARGET_URWLOCK_WRITE_OWNER) {
-        for (;;) {
-            if (!tcmpset_32(&target_urwlock->rw_state, state,
-                state & ~TARGET_URWLOCK_WRITE_OWNER)) {
-                __get_user(state, &target_urwlock->rw_state);
-                if (!(state & TARGET_URWLOCK_WRITE_OWNER)) {
-                    unlock_user_struct(target_urwlock,
-                        target_addr, 1);
-                    return -TARGET_EPERM;
-                }
-            } else {
-                break;
+         if (!tcmpset_32(&target_urwlock->rw_state, state,
+            state & ~TARGET_URWLOCK_WRITE_OWNER)) {
+            /* What - this doesn't looks right ??? */
+            __get_user(state, &target_urwlock->rw_state);
+            if (!(state & TARGET_URWLOCK_WRITE_OWNER)) {
+                unlock_user_struct(target_urwlock,
+                    target_addr, 1);
+                return -TARGET_EPERM;
             }
+            goto retry;
+        } else {
+            state &= ~TARGET_URWLOCK_WRITE_OWNER;
         }
     } else if (TARGET_URWLOCK_READER_COUNT(state) != 0) {
         /* decrement reader count */
-        for (;;) {
-            if (!tcmpset_32(&target_urwlock->rw_state, state, (state  - 1))) {
-                if (TARGET_URWLOCK_READER_COUNT(state) == 0) {
-                    unlock_user_struct(target_urwlock,
-                        target_addr, 1);
-                        return -TARGET_EPERM;
-                 }
-            } else {
-                break;
-            }
+        if (!tcmpset_32(&target_urwlock->rw_state, state, (state  - 1))) {
+            /* What - this doesn't looks right ??? */
+            if (TARGET_URWLOCK_READER_COUNT(state - 1) == 0) {
+                unlock_user_struct(target_urwlock,
+                target_addr, 1);
+                    return -TARGET_EPERM;
+             }
+             goto retry;
+        } else {
+            state -= 1;
         }
     } else {
         unlock_user_struct(target_urwlock, target_addr, 1);
```

**Comment by opsec** [comment]
I added such a patch to emulators/qemu-sbruno, rebuilt and re-tested by building
gettext-runtime. That still hangs during configure at

checking whether // is distinct from /... 

So, it does not seem to fix the issue.

**Comment by opsec** [comment]
See
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235057
for the reason why I'm testing this.

**Comment by kevans91** [comment]
Sorry, this got away from me. I'll go back and look at @strejda's patch within the week, because he raises valid points.

@opsec What version of FreeBSD is your build host?

**Comment by opsec** [comment]
13.0-CURRENT FreeBSD 13.0-CURRENT #2 r340445:343188M

**Comment by kevans91** [comment]
@strejda I re-read the kernel bits [1], and I think (if I read right) the originally proposed version is correct enough. The intent is to make sure that another thread didn't unset the flag (or drop the reader count to 0, both invalid state) out from underneath us. It would be cleaner to do this in one atomic operation like the kernel does, but the logic still works out correctly.

I updated this back to the original version added some comments -- the original structure (with infinite for) makes it a little easier to compare to kern_umtx for correctness.

[1] https://svnweb.freebsd.org/base/head/sys/kern/kern_umtx.c?revision=341727&view=markup#l3009

**Pull request merged**
