### PR TITLE
[PowerPC] Further fixes for PowerPC.

### PR DESCRIPTION
**Pull request by bdragon28**
Additional fixes needed as part of getting poudriere up and running to cross-build for powerpcspe from an amd64 host.

* The timeval / timespec padding was using the wrong check and were checking for MIPS / ARM instead of !I386.
* Handle POWERPC_EXCP_HV_EMU as a program exception. (Matches what linux-user does.)
* While fixing previous, I noticed that the error output was confusing (it was printing decimal with a hex prefix.) -- Fix this.

Poudriere side, I had to set BUILD_AS_NON_ROOT=no to fix an issue with execve calls not working.

I do not yet make it through the build of pkg, but it does get as far as the build phase before falling over now, which means things are in relatively good condition.

I suspect that I might be able to get a build with MAKE_JOBS_UNSAFE=yes, but I haven't completed testing yet. If it works, I'm going to start suspecting problems with interaction between multiple qemu-user processes.

### CODE REVIEW

**Comment by bsdimp** [comment]
Next time, please submit all changes with a signed off by line please. It will help when upstreaming

**Comment by kevans91** [comment]
They do all have a SOB?

**Comment by bsdimp** [comment]
Doh! I thought I didn't see them, but when checking again, they all have SOB...  Sorry for the needless grumps.

**Comment by kevans91** [comment]
No worries. :-) Can we push this entire operation over to the qemu-bsd-user you setup? It'd be nice to get/enable CI results for all PRs and also, e.g., check for SOB. I do the latter manually now, but CI giving advance notice to submitter would be better.

**Pull request merged**
