### PR TITLE
Bsd user

### PR DESCRIPTION
**Pull request by MikaelUrankar**
I'm seeing this error message:
/usr/local/bin/ghc
kevent: failed (Bad address)

here is the syscall trace (nevents and *eventlist are both 0):
kevent(8,-347058624,1,0,0,-347058648) = -1 errno=14 (Bad address)

### CODE REVIEW

**Comment by seanbruno** [comment]
Hrm ... I want to accept this change.  But it looks like by doing so I'd accept the "merge" stuff you did to this branch.  Can you clean up this pull request a bit or I can just direct commit the simple change you suggest.

**Comment by MikaelUrankar** [comment]
Do you know how I can clean up my mess? I'm struggling with git...

**Comment by seanbruno** [comment]
I guess ... delete your fork, refork and redo the pull request.  This stuff is so lame sometimes.

**Comment by splbio** [comment]
Jesus guys no...

Just make a new branch and git-cherry-pick the diff into it.

**Comment by seanbruno** [comment]
What Alfred said.  :-)

**Comment by splbio** [comment]
Give me two minutes, I'll give y'all the commands. :)

**Comment by splbio** [comment]
OK Mikael this will fix it:

First make a new branch based on the last commit in sean's "bsd-user" branch:

`git checkout -b kevent_fix d73740ab8ccf8379f7a6a1f59b24b499213468c2`

Now pick the commit into this branch:

`git cherry-pick c2a45f7d470d05416c13bfafa02c451d4f23435e`

Now push it as a new branch to your git repo:

`git push origin HEAD`

Now open a new pull request using github.



Ok, now your problem is that your branch "bsd-user" is now out of sync and messed up compared to sean's version of "bsd-user".

To fix this do the following:

`git push -f origin d73740ab8ccf8379f7a6a1f59b24b499213468c2:bsd-user`

From now on please branch before making a pull request to anyone! :)

**Comment by MikaelUrankar** [comment]
Thanks a lot Alfred!

**Comment by splbio** [comment]
Cool this is awesome stuff.  Thanks!

**Pull request closed without merging**
