### PR TITLE
Merge upstream v2.12.1 changes to add support for RISC-V architecture

### PR DESCRIPTION
**Pull request by markcorbinuk**
In order to add RISC-V user mode support the base version needs to be bumped to at least v2.12.0

### CODE REVIEW

**Comment by seanbruno** [comment]
Give us a bit before me merge to qemu-upstream.  We're trying to resolve a capsicum problem at the moment.

**Comment by markcorbinuk** [comment]
Any updates on this?

Thanks.

**Comment by bsdimp** [comment]
This will never be merged as a merge. That screws up our ability to move forward.
However, I'm finishing up updating my rebase branch so we can rebase the FreeBSD changes to a newer version of qemu. In the past, I've been reluctant to rebase forward because there's no test-suite to know if that's been screwed up or not. I'll see if I can get that pushed this week...

**Comment by markcorbinuk** [comment]
Thanks for the update.

**Comment by bsdimp** [comment]
To be clear, we want to get this to a point we can start having riscv userland stuff going, even if I have a small qibble about the means to get there...

**Comment by bsdimp** [comment]
I'll see if I can roll this into the rebasing I'm undertaking today...

**Comment by markcorbinuk** [comment]
This has been superseded by pull request #88

**Pull request closed without merging**
